### ISSUE TITLE
browser PDF generation stops to work with debian 11 chromium version 111

### ISSUE THREAD

**Issue by mrflos** [YesWiki/yeswiki-extension-publication#64]
I suppose it's a regression in chromium but after upgrading chromium package on debian 11 (to version 111), it stopped to work for the pdf generation.

Workaround : 

```bash
apt remove chromium chromium-common # remove latest version
apt install chromium=108.0.5359.94-1~deb11u1 chromium-common=108.0.5359.94-1~deb11u1 # install working version
apt-mark hold chromium # block updates for this package
apt-mark hold chromium-common # block updates for this package
```

This is probably not the best way to solve this problem, but it can probably help

**Comment by J9rem** [comment]
I have just updated composer packages.
Because of restriction on `php 7.3`, `chrome-php/chrome` keeps to revision `v1.7.2`.
But, the bug with `chrome 111` is solved by the revision `v1.8.1` of `chrome-php/chrome` : see notes : https://github.com/chrome-php/chrome/releases/tag/v1.8.1

So I supposed that the latest revision of `yeswiki-publication v1.2.8`, will continue not to work with `chromium 111`.

**Comment by thom4parisot** [comment]
It sounds like adding a Chromium startup flag (`--remote-allow-origins=*`) could fix this issue, as found in https://github.com/chrome-php/chrome/commit/a6faa979ae47aad5b8fb54e07cf1f74ebec023eb.

**Comment by J9rem** [comment]
Thanks @thom4parisot for the tip.
I had this `customFlag` in `config.yaml`
I hope it will work with `chromium 111`
